### ISSUE TITLE
软件什么时候支持多开

### ISSUE THREAD

**Issue by fgr178707** [wengx-unx/Minecraft-Lil-liver-helper#1]
我想两个账号都进行钓鱼
我再次运行提示我已经打开了
能不能一个软件操作多个窗口或者是软件多开几个
一个窗口运行一个软件

**Comment by iwengx** [comment]
目前你可以使用 Win 多用户的特点去解决这个需求

**Comment by fgr178707** [comment]
> 

那不过一直切换的
考虑考虑下个版本搞一个

**Comment by iwengx** [comment]
暂时还不打算弄多开（~~太破坏游戏平衡~~），但是不阻止玩家用其他方式多开（~~有点矛盾，但就这样吧~~）

**Comment by fgr178707** [comment]
我试过多开的话他都没有办法捕获路径手动找路径也找不着
只能显示     javaw->
然后就没了
