### ISSUE TITLE
自定义按键能做吗

### ISSUE THREAD

**Issue by fgr178707** [wengx-unx/Minecraft-Lil-liver-helper#3]
自定义开和隐藏游戏的自定义按键
有的服务器把F9和F10给用掉了能不
能不能改自定义按键

**Comment by iwengx** [comment]
尽量在下个版本进行更新

**Comment by fgr178707** [comment]
> 尽量在下个版本进行更新

下个版本更新啥时候暑假?

**Comment by iwengx** [comment]
自定义快捷键功能已经在 [Lil-liver-helper v2.5.2](https://github.com/wengx-unx/Minecraft-Lil-liver-helper/releases/tag/2.5.2) 版本中更新
