### ISSUE TITLE
高版本没法用

### ISSUE THREAD

**Issue by fgr178707** [wengx-unx/Minecraft-Lil-liver-helper#4]
为什么网易高版本用不了
现在是高版本用不了
自定义按键
啥时候能更新?

**Comment by iwengx** [comment]
经过测试，发现是在 Minecraft 1.13.x 版本之后，小肝助手的 键盘按键 指令在游戏中失效，鼠标 指令还可以用。暂时没有办法，如果找到解决的方案我会在这个 Issue 中回复。

**Comment by iwengx** [comment]
在版本 [Releases / v2.7.0](https://github.com/iwengx/Minecraft-Lil-liver-helper/releases/tag/2.7.0) 中已解决
