### ISSUE TITLE
[BUG] 有的值会重置

### ISSUE THREAD

**Issue by fgr178707** [wengx-unx/Minecraft-Lil-liver-helper#5]
选择,直接关闭程序，会导致以下数值重置
选择,右上角三个横线里面的退出软件,会导致以下数值重置
StartKey
HideKey
ProcessNameTxt

**Comment by fgr178707** [comment]
> 官网显示的版本是2.5.3，但是下载的版本是2.5.2
> 
> 选择,直接关闭程序，会导致以下数值重置 选择,右上角三个横线里面的退出软件,会导致以下数值重置 StartKey HideKey ProcessNameTxt

这个判定是游戏进程 如果有游戏进程他就不会重置，如果没有游戏进程退出软件的话，这三个数值会被重置

**Comment by iwengx** [comment]
版本 `v2.5.4` 已修复该问题
