### ISSUE TITLE
设置空白按键

### ISSUE THREAD

**Issue by fgr178707** [wengx-unx/Minecraft-Lil-liver-helper#8]
设置空白按键

比如说我用不上 "隐藏游戏" 通过 "删除键/ESC键"设置成空白，就是没有按键绑定

配置文件删除这个按键的快捷绑定  每次启动都报错
```
StartKey=F9
HideKey=
```
提示有问题
*当然了，把提示窗关掉也能用*
![7d72ab7d6a7f43f103bf0695f3ae2124](https://github.com/user-attachments/assets/9dd31bf7-f837-4ccf-a3bb-a8c99e36c41f)

**Comment by iwengx** [comment]
版本 `v2.5.6` 已添加该功能
