### ISSUE TITLE
希望可以添加方向键支持，这样就可以跑图挖矿了

### ISSUE THREAD

**Issue by ZzzhangLK** [wengx-unx/Minecraft-Lil-liver-helper#9]
希望可以添加方向键支持（比如按住w键），这样就可以跑图挖矿了

**Comment by ZzzhangLK** [comment]
还有一个疑问，就是钓鱼启动的时候为什么会全屏？版本1.20.4

**Comment by iwengx** [comment]
> 希望可以添加方向键支持（比如按住w键），这样就可以跑图挖矿了

如果想实现跑图挖矿的功能，单靠一个 W 键肯定是远远不够的，但是加入多个按键，这就有些类似自定义脚本相关的软件了。

**Comment by iwengx** [comment]
> 还有一个疑问，就是钓鱼启动的时候为什么会全屏？版本1.20.4

这个我有空测试一下，按理说不会出现这种情况才对。
